### ISSUE TITLE
warning: watchPosition() are deprecated

### ISSUE THREAD

**Issue by stefanocudini** [stefanocudini/leaflet-gps#15]
_getCurrentPosition()_ and _watchPosition()_ are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Someone know a definitive solution for this!??!**

**Comment by jstillwell** [comment]
If you just have your site on HTTPS it will be fine. The error/warning only occurs when on an HTTP(insecure) site.

**Comment by stefanocudini** [comment]
do you know any solution over plain HTTP?

**Comment by jstillwell** [comment]
Nope, that is kind of the point though. Google has been, rightfully so, getting tight on security. This is just part things that will be changing. SSL is cheap and worth it.

Check out the link they provide for more info.

**Comment by es6Test** [comment]
Why, what is the worst that can happen on http for this?

**Comment by jstillwell** [comment]
@es6test the only threat I see is some kind of man in the middle attack. If someone is listening, and you are not using https then everything you do is sent in plain text. This would enable them to know your location.

**Comment by erbing** [comment]
everything for safe

**Comment by gocanto** [comment]
so How can we get the user location through JS now? @jstillwell

**Comment by stefanocudini** [comment]
everything fork is appreciated ^_^

**Comment by gocanto** [comment]
of course.. But I just came across this conversations because I was browsing for a solution to that deprecate message. ```watchPosition() are deprecated```

which also appear when doing regulare geolocation as so: 

```javascript
if (navigator.geolocation) {

				var vm = this;
				navigator.geolocation.getCurrentPosition(function(position)
				{
					var geolocation = {
						lat: position.coords.latitude,
						lng: position.coords.longitude
					};

					var circle = new google.maps.Circle({
						center: geolocation,
						radius: position.coords.accuracy
					});

					vm.autocomplete.setBounds(circle.getBounds());
				});
			}
```

**Comment by Kevincifuentes** [comment]
I have the same issue, I can't use getCurrentPosition in just HTTP web page. Any comments for solving this using HTTP would be really apreciated. Thanks in advance!

**Comment by Zain-Ul-Abideen-1990** [comment]
Same issue, any luck?

**Comment by Kevincifuentes** [comment]
I just changed the web page to a https... don't know if there is another solution

**Comment by Zain-Ul-Abideen-1990** [comment]
Right but that's a worst case scenario will work when no hope. Is there any alternative?

**Comment by jstillwell** [comment]
I don't want to be mean but did you even read the explanation. You CANT do this without HTTPS. I just won't happen. The reason is that without HTTPS then others could steal your location. It's really very simple.

-----Original Message-----

**Comment by Zain-Ul-Abideen-1990** [comment]
ok and is there any alternative?

**Comment by jstillwell** [comment]
You are making it hard to be nice. No, in chrome there is no other way. Just read the warning. It says all you need to know. I will not be replying to this thread anymore. If you need clarification then you should consider a different occupation.

-----Original Message-----

**Comment by stefanocudini** [comment]
**FORK PLEASE!**
At this moment I don't have an Android device to do the tests

**Comment by hiteshthakor** [comment]
same error i am getting 
![console error](https://cloud.githubusercontent.com/assets/19173057/15154000/1de54e70-16f9-11e6-90e4-98601f78f55e.png)

please help me i am stuck

**Comment by Zain-Ul-Abideen-1990** [comment]
Please use it with SSL then no issues.
here is the link: http://m.clratings.com/test.html

**Comment by Zain-Ul-Abideen-1990** [comment]
I did yesterday and it's been fine for me.

**Comment by vicmonmena** [comment]
Hi!

Any alternative for development environment?

Thanks!

**Comment by hiteshthakor** [comment]
@Zain-Ul-Abideen-1990  i am not able to open above link

**Comment by Zain-Ul-Abideen-1990** [comment]
I have removed the file from the server but things works fine with HTTPS.

**Comment by hiteshthakor** [comment]
it  working fine with https but not with htto

**Comment by Zain-Ul-Abideen-1990** [comment]
Yes, it works with https not http.

**Comment by stefanocudini** [comment]
uoh then... unique solution is using HTTPS!!?  DAMN!

**Comment by tvelf009** [comment]
You can run chrome with the --unsafely-treat-insecure-origin-as-secure="http://example.com" flag (replacing "example.com" with the origin you actually want to test), which will treat that origin as secure for this session. Note that you also need to include the --user-data-dir=/test/only/profile/dir to create a fresh testing profile for the flag to work.

For example
if use Windows, Click Start and run.

    chrome --unsafely-treat-insecure-origin-as-secure="http://localhost:8100"  --user-data-dir=C:\testprofile

**Comment by San-Jeevan** [comment]
Its the latest chrome browser update that creates this issue.
Works fine in IE and Firefox. I think its time the people got rough with Googles attitude of screwing people over like this. I don't care if its security related. They should leave the http option open.
Even if its security related,  governments like the american, british etc can just go to the CA of the certificate and ask for the private key so they can decrypt the encrypted traffic. Infact I think they have intergrated automatically retrieval of private keys from CAs in they surveillence tool.

From now on I am deleting chrome and going Firefox.

**Comment by muhiddingithub** [comment]
This work only HTTPS not HTTP, testing localhost only can by FireFox

**Comment by raselcse10** [comment]
Google Chrome has deprecated this feature from **version 50**. Below 50 it will work . Now it will work only for **HTTPS**.

**Comment by taufeek6** [comment]
In my case it is working with firefox but not with crome.

**Comment by geosmiles** [comment]
Is there a work around this yet?

**Comment by IsraelDCastro** [comment]
I'm working in localhost, i read the geolocation would work fine if i work in localhost, but i hava an Error all the time: getCurrentPosition() and watchPosition() no longer work on insecure origins. 

I need a solution, please help me

**Comment by stefanocudini** [comment]
you need use HTTPS in your local web server

**Comment by IsraelDCastro** [comment]
Thanks, how can I get a Https local web?

**Comment by felipedspereira** [comment]
@IsraelDCastro you can use it with **localhost**. In chrome this still working

**Comment by NavruzJn** [comment]
Hi guys, so is there any solution to get current geo location withoud https?
Or can give me links How to switch https to https?

**Comment by hmzaabasi** [comment]
> Hi guys, so is there any solution to get current geo location withoud https?
> Or can give me links How to switch https to https?

The warning clearly states that it's not possible "[Deprecation] getCurrentPosition() and watchPosition() **_no longer work on insecure origins_**. To use this feature, you should consider switching your application to a secure origin,"

**Comment by San-Jeevan** [comment]
you can use ngrok for local testing.
otherwise letsencrypt is a free solution
