### ISSUE TITLE
locate loadingIcon spinner

### ISSUE THREAD

**Issue by kaio328** [stefanocudini/leaflet-gps#22]
Your locate plugin has the most accuracy and is the smoothest one for leaflet. Great Job!

Any idea how to implement a spinner icon to the locate-button (with font-awesome) which should appear only when "map.locate" is trying to find the current position of the user? 

here's an example: https://www.domoritz.de/leaflet-locatecontrol/demo/

**Comment by stefanocudini** [comment]
you can simply use ths:
http://labs.easyblog.it/maps/leaflet-loader/
