### ISSUE TITLE
Autoupdate marker position

### ISSUE THREAD

**Issue by kingstakh** [stefanocudini/leaflet-gps#7]
Be cool have option for autoupdating marker position by time (min, sec). 
Example:
    options: {  
        autoActive: false,      //activate control at startup
        autoCenter: false,      //move map when gps location change
        maxZoom: null,          //max zoom for autoCenter
                autoUpdate: 60          // autoupdate my position via GPS in sec
Now marker position updating if move map or if change map zoom. 
But marker not move automaticaly if I go or if I ride.

**Comment by swordsteel** [comment]
I absolutely agree. This plugin would be nearly perfect if it could autoupdate without having to refresh the page, giving a realtime view of the gps device being tracked.

**Comment by vchigne** [comment]
+1 for this

**Comment by osro** [comment]
+1 for this also

**Comment by stefanocudini** [comment]
I accept any fork that solves part of the problem

**Comment by stefanocudini** [comment]
from version 1.6.0 it work!
